controller_list:
  - name: fake_right_arm_controller
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: fake_left_arm_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
  - name: fake_both_arms_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
  - name: fake_right_hand_controller
    joints:
      - RHand
  - name: fake_left_hand_controller
    joints:
      - LHand
  - name: fake_head_controller
    joints:
      - HeadYaw
      - HeadPitch
  - name: fake_waist_controller
    joints:
      - HipPitch
      - HipRoll
  - name: fake_entire_upper_body_controller
    joints:
      - HipPitch
      - HipRoll
      - HeadYaw
      - HeadPitch
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw